language: node_js
node_js:
  - "8.9.1"
cache:
  directories:
    - "node_modules"
notifications:
  slack: gamesharegroup:52VErVS4AE5O3A8MyVqDPbRH
dist: trusty
sudo: false  # no need for virtualization.
addons:
  chrome: stable
before_deploy:
  - rm -rf {__tests__,scrum_docs,src}
deploy:
  provider: heroku
  skip_cleanup: true
  app: gameshare-app
  api_key:
    secure: MSWcJC2IfDuSeEepnCAIqwJV+vad4xpMfT6W8PG+lvFuCLVVwXbMjMyfO4d5Hlfo77R8cBoZer3kt4a4/jjvzuRvc/9sr2uZoV8oIwXqXc+PJ6EtHuner7C2yMk1zgkDtK1oW2A3DhWcb28NmuuN1xJE4McCSCttSvkAorbOQ2aSAB4MqtUpLit3a+ZXc/ImZJTDpMpaQmkAWbrBQUR8LH+KPRrMRxEVKd7g5gCzPNqU8+uEVmAQGsMuEXKcLwcc0ZDjG2kkDdlfKLy6TvJYIrcJh5KsE9JXglclCKWvmGdwsiXhBr3liZCvw97EgLmVcwTUZ0N+q2HKrxvSDh8dVBuWiMeOeTo0Cp+z/hw8lLHKf6WNHn9erXRcYtSqbgkM7gPJr2PhQLGtzpP+pTmkkOyaZXAg5ZlxaUG/tTAViPR+gRxjJF3Dg7Kfc0aA0drJqtykYE8Yy3OLVerksEwqfA2yhFSmFiGtUKEDv8H9ORky5sGHI2xrTZjRgjwswJHQgcufMpIkx58Fb006oz8U3owUGDN3U7QsJUXnW4HknsCnSi6P72IVXe3o4x/PGyElFoEIVx+/CD9euEzpCnGCH9bQUKBPHkUGsEGbF3RvxrugmSjPLYq6fzouif2L3h8dFunxEkoTHO8UFpxlMvrsrAo3rgWS8IljHqvtahYRJrk=