language: node_js
node_js:
- 8.9.1
cache:
  directories:
  - node_modules
before_script:
- npm run build
dist: trusty
sudo: false
addons:
  chrome: stable
before_deploy:
- rm -rf {__tests__,scrum_docs,src}
deploy:
  provider: heroku
  api_key:
    secure: pFwoqp74Z8xz4/tfzidFUgPOuF6cN0nTCIpXzuRUHwo+XGwflGY5gKk2ZHm24OQzNy6b/V5N9ujkgZmIoWqO8tXKibZFeLseVVfAb/2RRQgtFZ86RUlz6agIUopE4Z0MrMB/fmUYZmjoz0/eL4CvPnHgIkHwmmFZBH+abD5F3qUCIvN6ErVq3q37jDOSn4H5N7Yh/S5Ab31rGGZA/74pSw8QjrTsupEiyNlNKujH1TZIEJ5TrY7FqHoU1ejvbmMngQpmQ6eKaDV1CmBT6QfSlDrZ9Yffg8bBmoxo6qjbb5oDSCWfq7TW9rx7Y1xPNktcdR2Hsr3LLkdWfrzrFyjOH6r4Qf4UIZQGm4hCnK2tONTwrZvDzSN51xeOmbNkSMOGMljC1iEGHd5udYSs+XzH5Bzz4piEuymhmOqEHz1/MsJyFMFxH+cq1L5w5YOOJrnCi9g/lBBYXdQIV25hPvF20EqTkgam5gDJKifSTXfmLPZz79tu3YoaLW/qKc2irYCN8TAZ7WfpVBCWrJpDfT+YQDIhLvGMNU1HQTasZrpttzDJVqLMbAJXZI0HG14uuqCc+Ifjwe8W22mvnuW9hzkkpMqAzaAVw9m6f0fFpGBYBtYJeAVf/JBLRIbK3JA1R1JZTmIoBtx+cR/MjyRv3RQZbsEOwz7pUt6nbim76Mk+xLg=
  app: GameShare
  skip_cleanup: true
  on:
    repo: wyattades/GameShare
