language: node_js
node_js:
- 8.9.1
cache:
  directories:
  - node_modules
before_script:
- npm run build
dist: trusty
sudo: false
addons:
  chrome: stable
before_deploy:
- rm -rf {__tests__,scrum_docs,src}
deploy:
  provider: heroku
  skip_cleanup: true
  app: gameshare-app
  api_key:
    secure: ITdUjS4piFkhiRytvgmsm3y/i3Euu4jcWSuGG6hEkjrqBfc2cVbDCdSiHsuND52RZ3VJIMSZ2v9lPEE92LSTFATanqUNSrlpZSgntQPGI+Lmhd+m9sBu6TLf+kpzihWs6uxf/ShYEeNeoqUs8MZfJckhKUefd2l3XMMlamqJqYdb7ZOsq7H3iyPh+SYg6+g8hAHw4N2UCiE2QLKyVEtmv5/rie+7wb7rMlVF1GH2oQtP+9ljpKgSw2BzFn1YCY3XLqeEimG7lAToS85tkepAuIkeM3W6MfkGm6eYBp7C3q/AZ7MEFvopH3lnns+p37980mO9lJYGaxpYpJ80WOoNYANP+9HJu0ArpeOwiY6gX3kFxVFfk7wWRchbZSdfeK8oXSygMo52sTqQb3TBdvlQH5cfAgKF3uLTWvSQSzxZoPiVOXEcY3pLJ0ELeYGeYPL6VIsaaHHWclmOTL/hsqHs4lrBDu0eKWLUWjBpBMEVuJtVAjjsKsAOeGrHCWH7Tm8cANoT0dzD7gD+ftYIVdbLfELW4q48SrtsfKIotAL6a/dx73OJPG5h4wa2xKX3Id03IJ5fsPRJ8t62tXBP0TiOpiWt4oQ1uWWUzPZypkfjEFpXQ89jZSEeK+urB7PDeZaBBr+ZW8Fv6aDqJB5VmDQrTwWekG9gRARouOJ1oOQj9Io=
