language: node_js
node_js:
- 8.9.1
cache:
  directories:
  - node_modules
before_script:
- npm run build
dist: trusty
sudo: false
addons:
  chrome: stable
before_deploy:
- rm -rf {__tests__,scrum_docs,src}
deploy:
  provider: heroku
  api_key:
    secure: Oj4iCtpZHRPsVQ0DwETYzlDx7qvJdbwnWfNWmgDWLHG4XlESwe/FOTBOfFlPiVVJRkdW8ayVeKYJp+OdB3WMkwJKnPmHX8hKRGlMI+le7FyDVYJAt1v1BCI64tOc1uPmpicE9JfdAa9m+/4UV7a2kQ1v7ngYBQm5yrd1evtBTFYTsyNld9DN1ib4D1hS8zIzUOP/7zmFuTvBAxflMxRXejJbapaNZVbaZgE0kLGUlqLQ25IW6+hLO6zm+lNnTE1MaEhd8P6AKv+wgpGTCHbBinhNE1lpJ3yzZLhjfwunMI0iqJZExm1fksId//L2BcggtoGiAJVsgavZ75+jt9uR/wGSYo4eSUv5EEFI+m84jwy7uGvD9KYBRGi+T9R+li6HnSFFFp+DRPIfJ9KPiQAsqnqkD2o5JNlhNcifnGkwdkQK2H00cPT3oBRAItJmM8kNwaTaXcNYmiVhcJeoOjPgbuS1oJWfLdqvG+s7C+l51HR1J3qvcBAhwZTItz9HKb2U75svIL2plbwaPrfWPAEhtt5rTR0H0hEy4QwGYXCe8Jne6ZFpChW2eXB2s41p1PW2jMMspztKk+ETvSH/2zc9dTWJvhLpbe958el8/RJ3MZl+tV1xL4wokBASAQa68u6Krz3svLTMdcjR1EkDk+iKwS/yHaxUgzFGHFonZea1n/s=
  app: gameshare-app
  skip_cleanup: true
  on:
    repo: wyattades/GameShare
