language: node_js
node_js:
  - "8.9.1"
cache:
  directories:
    - "node_modules"
notifications:
  slack: gamesharegroup:52VErVS4AE5O3A8MyVqDPbRH
dist: trusty
sudo: false  # no need for virtualization.
addons:
  chrome: stable
